<a href="https://colab.research.google.com/github/hkyoo52/CV/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pytorch 장점**
1. Define by Run(실행하면서 그래프 생성)a -> 즉시 확인 가능
2. GPU support, Goot community
3. 사용하기 편함

**Pytorch 특징**
* Numpy로 표현
* 자동미분 지원(AutoGrad)
* 다양한 형태의 함수와 모델 지원

## AutoGrad

In [ ]:
# numpy 버전
import numpy as np
n_array=np.arange(10).reshape(2,5)
print(n_array)
print('ndim : ',n_array.ndim,'shape : ',n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim :  2 shape :  (2, 5)


In [ ]:
#pytorch
import torch
t_array=torch.FloatTensor(n_array)
print(t_array)
print('n_dim : ',t_array.ndim, 'shape : ',t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
n_dim :  2 shape :  torch.Size([2, 5])


In [ ]:
# numpy에서 쓰는 코드 거의 다 사용 가능
data=[[3,5,10,],[10,5,50],[1,5,10]]
x_data=torch.tensor(data)

print('slice : ', x_data[1:])
print('slice : ', x_data[:2,1:])
print('flatten : ',x_data.flatten())
print('텐서 생성 : ',torch.ones_like(x_data))
print('numpy 변경 ',x_data.numpy())
print('shape : ',x_data.shape)
print('dtype : ',x_data.dtype)

slice :  tensor([[10,  5, 50],
        [ 1,  5, 10]])
slice :  tensor([[ 5, 10],
        [ 5, 50]])
flatten :  tensor([ 3,  5, 10, 10,  5, 50,  1,  5, 10])
텐서 생성 :  tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
numpy 변경  [[ 3  5 10]
 [10  5 50]
 [ 1  5 10]]
shape :  torch.Size([3, 3])
dtype :  torch.int64


In [ ]:
# cpu 사용 -> cpu, gpu 사용 -> cuda
x_data.device
if torch.cuda.is_available():
  x_data=x_data.to('cuda')
x_data.device

device(type='cpu')

## **Tensor handling**
* view : reshape와 동일하게 tensor의 shape 변환
* squeeze : 차원의 개수가 1인 차원을 삭제(압축)
* unsqueeze : 차원의 개수가 1인 차원추가

In [ ]:
tensor_ex=torch.rand(size=(2,3,2))
tensor_ex.view([-1,6])

tensor([[0.6726, 0.9337, 0.8388, 0.6272, 0.3991, 0.5167],
        [0.6711, 0.6075, 0.9608, 0.5655, 0.4674, 0.5178]])

In [ ]:
# view는 동일 메모리에 형태만 다르게 하는 거임!!!
a=torch.zeros(3,2)
b=a.view(2,3)
a.fill_(1)
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# squeeze, unsqueeze
tensor_ex=torch.rand(size=(2,1,2))
tensor_ex.squeeze().shape

torch.Size([2, 2])

In [ ]:
tensor_ex=torch.rand(size=(2,2))
tensor_ex.unsqueeze(0).shape

torch.Size([1, 2, 2])

In [ ]:
tensor_ex=torch.rand(size=(2,2))
tensor_ex.unsqueeze(1).shape

torch.Size([2, 1, 2])

## **tensor operation**
* +, - : 같은 차원에서만 사용 가능 
* mm : 행열간의 내적 (벡터간의 연산X)
* dot : 행렬간의 곱셈
* matmul : 알아서 브로드캐스팅해서 내적을 함

**일반적으로 tensor에 첫 차원은 batch를 의미한다!!**

In [ ]:
n1=np.arange(10).reshape(2,5)
t1=torch.FloatTensor(n1)
n2=np.arange(10).reshape(5,2)
t2=torch.FloatTensor(n2)
print(t1)
print(t2)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])


In [ ]:
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [ ]:
t1.dot(t1)

RuntimeError: ignored

In [ ]:
  # mm은 벡터간의 연산은 할 수 없다.
a=torch.rand(10)
b=torch.rand(10)
a.mm(b)

RuntimeError: ignored

In [ ]:
a.matmul(b)

tensor(3.4360)

## **딥러닝 module**
torch.nn.functional as F

In [ ]:
import torch
import torch.nn.functional as F

tensor=torch.FloatTensor([0.5,0.7,0.1])
h_tensor=F.softmax(tensor,dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [ ]:
y=torch.randint(5,(10,5))
y_label=y.argmax(dim=1)
print(y)
print(y_label)

tensor([[3, 0, 2, 1, 1],
        [1, 2, 0, 4, 3],
        [2, 3, 4, 0, 0],
        [1, 4, 1, 3, 3],
        [3, 1, 3, 0, 4],
        [4, 2, 3, 2, 4],
        [2, 3, 4, 0, 3],
        [0, 3, 4, 0, 3],
        [2, 0, 1, 0, 4],
        [0, 1, 0, 1, 4]])
tensor([0, 3, 2, 1, 4, 0, 2, 2, 4, 4])


In [ ]:
# one-hot 인코딩
torch.nn.functional.one_hot(y_label)

tensor([[1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1]])

In [ ]:
# cartesian_prod : list a와 list b의 가능한 모든 조합
a=[1,2,3]
b=[4,5]
tensor_a=torch.tensor(a)
tensor_b=torch.tensor(b)
torch.cartesian_prod(tensor_a,tensor_b)

tensor([[1, 4],
        [1, 5],
        [2, 4],
        [2, 5],
        [3, 4],
        [3, 5]])

In [ ]:
# requires_grad로 미분 가능 형태로 만듬
# backward()로 미분 사용
w=torch.tensor(2.0,requires_grad=True)
y=w**2
z=10*y+25       # z=10w**2
z.backward()    # y'=20w
w.grad

tensor(40.)

$$Q=3a^3-b^2$$



In [ ]:
a=torch.tensor([2.,3.],requires_grad=True)
b=torch.tensor([6.,4.],requires_grad=True)
Q=3*a**3-b**2
external_grad=torch.tensor([1.,1.])
Q.backward(gradient=external_grad)    #gradient 크기값을 넣어줌
print(a.grad)
print(b.grad)

tensor([36., 81.])
tensor([-12.,  -8.])


## **파이토치 모듈**
https://github.com/victoresque/pytorch-template

![image](https://user-images.githubusercontent.com/63588046/150713042-d627f609-76ac-4a3e-8505-692f9b31861e.png)


cmd 코드

git clone https://github.com/victoresque/pytorch-template.git
cd pytorch-template
conda activate torch
python new_project.py MyProject
cd MyProject\
code .


### **colab에서 연동하기**

In [ ]:
!pip3 install torch
!pip3 install torchvision

In [ ]:
!git clone https://github.com/victoresque/pytorch-template.git

Cloning into 'pytorch-template'...
remote: Enumerating objects: 1516, done.
remote: Total 1516 (delta 0), reused 0 (delta 0), pack-reused 1516
Receiving objects: 100% (1516/1516), 288.08 KiB | 16.00 MiB/s, done.
Resolving deltas: 100% (848/848), done.


In [ ]:
!ls

drive  pytorch-template  sample_data


In [ ]:
%cd /content/pytorch-template
!python new_project.py MNIST-example

/content/pytorch-template
New project initialized at /content/pytorch-template/MNIST-example


In [ ]:
NGROK_TOKEN = '2482F7wzrm0zOoJfvPz64DTMc21_8U5CJfrqcX5Fz4RtaHSf'
PASSWORD = 'gksgh123'

In [ ]:
pip install colab-ssh

In [ ]:
from colab_ssh import launch_ssh
launch_ssh(NGROK_TOKEN,PASSWORD)

we highly recommend that update your code by following this documentation https://github.com/WassimBenzarti/colab-ssh#getting-started
Successfully running 4.tcp.ngrok.io:14976
[Optional] You can also connect with VSCode SSH Remote extension using this configuration:

  Host google_colab_ssh
    HostName 4.tcp.ngrok.io
    User root
    Port 14976
    


In [ ]:
# __getitem__ :  config에 값들을 test[config] 식으로 넣어서 값을 매우 쉽게 불러온다
# config.json에 내용들을 끼워넣어서 config로 나중에 넣어서 문제를 해결한다.


class Test(object):
  def __getitem__(self,items):
    print(type(items),items)

test=Test()
test[5]
test[5:65:5]
test['GeeksforGeeks']
test[1,'x',10.0]
test['a':'z':2]
test[object()]

<class 'int'> 5
<class 'slice'> slice(5, 65, 5)
<class 'str'> GeeksforGeeks
<class 'tuple'> (1, 'x', 10.0)
<class 'slice'> slice('a', 'z', 2)
<class 'object'> <object object at 0x7f7d7c4f5b20>
